class CheckoutPageLocator:
    checkout_your_information_page = 'Checkout: Your Information'
    checkout_page_title = '//span[@class="title"]'
    checkout_button = '//button[@id="checkout"]'
    cancel_button = '//button[@id="cancel"]'
    continue_button = '//input[@id="continue"]'
    first_name = '//input[@id="first-name"]'
    last_name = '//input[@id="last-name"]'
    postal_code = '//input[@id="postal-code"]'
    error_locator = '//h3[@data-test="error"]'
    checkout_overview_page = 'Checkout: Overview'
    payment_information = '//div[text()="Payment Information"]'
    shipping_information = '//div[text()="Shipping Information"]'
    price_total = '//div[text()="Price Total"]'
    finish_button = '//button[@id="finish"]'
    checkout_complete_page = 'Checkout: Complete!'
    thank_you_for_your_order = '//h2[text()="Thank you for your order!"]'
    back_to_home_button = '//button[@id="back-to-products"]'
