class CartPageLocator:
    home_page_title = '//span[@class="title" and text()="Products"]'
    app_logo = '//div[@class="app_logo"]'
    menu_button = 'id=react-burger-menu-btn'
    shopping_cart_link = '//a[@class="shopping_cart_link"]'
    product_sort_container = '//select[@class="product_sort_container"]'
    twitter_symbol = '//a[@href="https://twitter.com/saucelabs"]'
    facebook_symbol = '//a[@href="https://www.facebook.com/saucelabs"]'
    linkedin_symbol = '//a[@href="https://www.linkedin.com/company/sauce-labs/"]'
    inventory_item = '//div[@class="inventory_item"]/[inventory_no]'
    inventory_item_image = '//div[@class="inventory_item"][inventory_no]/div[@class="inventory_item_img"]//img'
    inventory_item_name = '//div[@class="inventory_item"][inventory_no]//div[@class="inventory_item_name "]'
    add_to_cart_button = '//div[@class="inventory_item"][inventory_no]//div[@class="pricebar"]/button'
    remove_from_cart_button_homepage = '//div[@class="inventory_item"][inventory_no]//div[@class="pricebar"]/button'
    inventory_price = '//div[@class="inventory_item"][inventory_no]//div[@class="pricebar"]/div'
    back_to_products = '//button[@class="btn btn_secondary back btn_large inventory_details_back_button"]'
    cart_item_name = '//div[@class="cart_item"][inventory_no]//div[@class="inventory_item_name"]'
    cart_item_price = '//div[@class="cart_item"][inventory_no]//div[@class="inventory_item_price"]'
    continue_shopping_button = '//button[text()="Continue Shopping"]'
    cart_item = '//div[@class="cart_item"]'
    remove_from_cart_button_cart = '//div[@class="cart_item"][inventory_no]//div[@class="item_pricebar"]/button'
    inventory_details_name = '//div[@class="inventory_details"][1]//div[@class="inventory_details_name large_size"]'
    inventory_details_price = '//div[@class="inventory_details"][1]//div[@class="inventory_details_price"]'
    inventory_details_image = '//div[@class="inventory_details"][1]//div[@class="inventory_details_img_container"]/img'
    cart_page_title = '//span[text()="Your Cart"]'
    quantity_text = '//div[text()="QTY"]'
    description_text = '//div[text()="Description"]'
